version: '3.3'
 services:
   petclinic:
     image: PetclinicMaven
     ports:
      - "8080:8080"
     environment:
       DATABASE_NAME: xxxx
       DB_USER: xxxx
       DB_PASSWORD: xxxx
     labels:
       com.example.description: "webapp"
       com.example.department: "petclinic"
       com.example.label-with-empty-value: ""
     deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M  
  networks:
    overlay:
